# NumPy Básico – Operações e Exercícios
Autor: Matheus Leite


## Seção 1: Criação de Arrays

In [68]:
import numpy as np

# 1.1 Crie um array 1D com os números de 0 a 9
a = np.arange(0, 10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
# 1.2 Crie um array 2D de tamanho 3x3, preenchido apenas com o número 7
b = np.full((3, 3), 7)
print(b)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [66]:
# 1.3 Gere uma matriz identidade 4x4
c = np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Seção 2: Indexação e Slicing

In [ ]:
# 2.1 Trabalhar com a matriz `mat`
mat = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# a) Segunda linha
print(mat[1])
# b) Última coluna
print(mat[:, 2])
# c) Elemento central
print(mat[1, 1])



[40 50 60]
[30 60 90]
50
[[10 20 30]
 [40 50 60]
 [70  0 90]]


In [65]:
# 2.2 Modificar valor 80 para 0
mat[2, 1] = 0
print(mat)

[[10 20 30]
 [40 50 60]
 [70  0 90]]


## Seção 3: Operações com Arrays

In [64]:
# 3.1 Soma, multiplicação, média e máximo
f = np.arange(2, 10, 2)
g = np.arange(1, 9, 2)
print(f"{f} \n{g}")
print("Soma: ", f + g)
print("Multiplicação: ", f * g)
print("Média de f: ", np.mean(f))
print("Máximo de g: ", np.max(g))

[2 4 6 8] 
[1 3 5 7]
Soma:  [ 3  7 11 15]
Multiplicação:  [ 2 12 30 56]
Média de f:  5.0
Máximo de g:  7


In [63]:
# 3.2 15 valores igualmente espaçados entre 0 e 5
espaços = np.linspace(0, 5, 15)
print(espaços)

[0.         0.35714286 0.71428571 1.07142857 1.42857143 1.78571429
 2.14285714 2.5        2.85714286 3.21428571 3.57142857 3.92857143
 4.28571429 4.64285714 5.        ]


## Seção 4: Desafios

In [62]:
# 4.1 Matriz 5x5 com valores de 1 a 25
i = np.arange(1, 26).reshape(5, 5)
print("Original:", i)
print("Flip horizontal:\n", i[:, ::-1])
print("Flip vertical:\n", i[::-1, :])

Original: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Flip horizontal:
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]
Flip vertical:
 [[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [61]:
# 4.2 Soma da diagonal principal
print("Soma da diagonal: ", np.trace(i))

Soma da diagonal:  65


In [60]:
# 4.3 Contar quantos valores de 1 a 50 são múltiplos de 3
arr = np.arange(1, 51)
print(arr)
print("Total de multiplos de 3: ", np.sum(arr % 3 == 0))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Total de multiplos de 3:  16
